In [1]:
import numpy as np 
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df = pd.read_csv('covid_toy.csv')

In [11]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [17]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train,y_test = train_test_split(df.drop(columns =['has_covid']),df['has_covid'],test_size = 0.2)

In [21]:
X_train

age  gender  fever   cough     city
25   23    Male    NaN    Mild   Mumbai
46   19  Female  101.0    Mild   Mumbai
27   33  Female  102.0  Strong    Delhi
56   71    Male    NaN  Strong  Kolkata
28   16    Male  104.0    Mild  Kolkata
..  ...     ...    ...     ...      ...
26   19  Female  100.0    Mild  Kolkata
54   60  Female   99.0    Mild   Mumbai
0    60    Male  103.0    Mild  Kolkata
33   26  Female   98.0    Mild  Kolkata
79   48  Female  103.0    Mild  Kolkata

[80 rows x 5 columns]

In [23]:
y_train

25     No
46     No
27     No
56     No
28     No
     ... 
26    Yes
54    Yes
0      No
33     No
79    Yes
Name: has_covid, Length: 80, dtype: object

# 1. Normal way -------------->

In [26]:
# adding simple imputer to fever columns ------------------------->
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data ----------------->
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [28]:
X_train_fever

array([[100.91549296],
       [101.        ],
       [102.        ],
       [100.91549296],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [100.91549296],
       [102.        ],
       [100.91549296],
       [101.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [ 99.        ],
       [100.        ],
       [100.91549296],
       [100.        ],
       [101.        ],
       [100.91549296],
       [104.        ],
       [102.        ],
       [100.91549296],
       [101.        ],
       [101.        ],
       [100.91549296],
       [100.        ],
       [102.        ],
       [ 98

In [30]:
# Ordinal Encoding => cough
oe = OrdinalEncoder(categories = [['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data --------------------------->
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [32]:
X_train_cough.shape

(80, 1)

In [38]:
# OneHotEncoding => gender, city
ohe = OneHotEncoder(drop ='first',sparse_output = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data ---------------------------------------->
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

array([[1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],


In [40]:
X_train_gender_city.shape

(80, 4)

In [42]:
# Extracting Age ------------------------------------->
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

#also the test data --------------------------->
X_test_age = X_test.drop(columns =['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [44]:
X_train_age

array([[23],
       [19],
       [33],
       [71],
       [16],
       [27],
       [49],
       [ 5],
       [18],
       [79],
       [49],
       [42],
       [42],
       [82],
       [34],
       [34],
       [69],
       [14],
       [54],
       [24],
       [11],
       [64],
       [69],
       [73],
       [40],
       [71],
       [51],
       [47],
       [59],
       [72],
       [19],
       [82],
       [27],
       [47],
       [38],
       [ 6],
       [69],
       [75],
       [51],
       [65],
       [20],
       [27],
       [82],
       [65],
       [34],
       [25],
       [12],
       [68],
       [ 8],
       [42],
       [15],
       [66],
       [70],
       [16],
       [14],
       [56],
       [13],
       [73],
       [83],
       [34],
       [ 5],
       [64],
       [38],
       [80],
       [20],
       [74],
       [49],
       [44],
       [55],
       [50],
       [10],
       [19],
       [12],
       [81],
       [25],
       [19],
       [60],

In [52]:
# axis=1 means => You are **concatenating arrays horizontally (i.e., column-wise).Each array in the tuple will be added as additional columns.

X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis =1)

# also the test data ----------------->
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis =1)

X_train_transformed.shape

(80, 7)

In [50]:
X_train_transformed

array([[ 23.        , 100.91549296,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        , 100.91549296,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 16.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 18.        , 104.        ,   0.        ,   0.        ,
          0.    

# 2. Smart Way ================> 

In [55]:
from sklearn.compose import ColumnTransformer

In [57]:
transformer = ColumnTransformer( transformers =[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories =[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output = False, drop='first'),['gender','city'])
], remainder='passthrough')

In [59]:
transformer.fit_transform(X_train)

array([[100.91549296,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [100.91549296,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [61]:
transformer.fit_transform(X_train).shape

(80, 7)

In [63]:
transformer.fit_transform(X_test).shape

(20, 7)

In [65]:
transformer.fit_transform(X_test)

array([[100.57894737,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  65.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.    