# Classification Metrics(Part-1) =>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("heart.csv")

In [33]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [35]:
df.shape

(303, 14)

In [37]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,0:-1] , df.iloc[:,-1], test_size = 0.2 , random_state = 2)

### df.iloc[:, 0:-1] =>	Selects all rows and all columns except the last column. This is your features (X).
### df.iloc[:, -1] =>	Selects all rows and only the last column. This is your target (y).

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [41]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [43]:
clf1.fit(X_train , y_train)
clf2.fit(X_train , y_train)

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [45]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score , confusion_matrix

print("Accuracy of Logistic Regression: " , accuracy_score(y_test , y_pred1))
print("Accuracy of Decision Tree Classifier: " , accuracy_score(y_test , y_pred2))

Accuracy of Logistic Regression:  0.9016393442622951
Accuracy of Decision Tree Classifier:  0.8360655737704918


## Confusion Matrix=>

In [49]:
confusion_matrix(y_test , y_pred1)

array([[26,  6],
       [ 0, 29]], dtype=int64)

In [51]:
confusion_matrix(y_test , y_pred2)

array([[24,  8],
       [ 2, 27]], dtype=int64)

# Confusion Matrix for Multi-Classification Problem =>

In [75]:
df2 = pd.read_csv("iris.csv")

In [77]:
df2.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
142           5.8          2.7           5.1          1.9   virginica
98            5.1          2.5           3.0          1.1  versicolor
119           6.0          2.2           5.0          1.5   virginica
7             5.0          3.4           1.5          0.2      setosa
51            6.4          3.2           4.5          1.5  versicolor

In [79]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df2['species'] = encoder.fit_transform(df2['species'])

In [103]:
df2.sample(5)

sepal_length  sepal_width  petal_length  petal_width  species
136           6.3          3.4           5.6          2.4        2
83            6.0          2.7           5.1          1.6        1
0             5.1          3.5           1.4          0.2        0
146           6.3          2.5           5.0          1.9        2
117           7.7          3.8           6.7          2.2        2

In [105]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df2.iloc[:,0:-1],df2.iloc[:,-1],test_size=0.2,random_state=1)

In [107]:
clf3 = LogisticRegression()
clf4 = DecisionTreeClassifier()

In [109]:
clf3.fit(X_train , y_train)
clf4.fit(X_train , y_train)


DecisionTreeClassifier()

In [111]:
print(y_test.shape)
y_pred3 = clf3.predict(X_test)
y_pred4 = clf4.predict(X_test)
print(y_pred3)
print(y_pred3.shape)


print(y_pred4)

(30,)
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2]
(30,)
[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2]


In [113]:
print("Accuracy of Logistic Regression: " , accuracy_score(y_test , y_pred3))
print("Accuracy of Decision Tree Classifier: " , accuracy_score(y_test , y_pred4))

Accuracy of Logistic Regression:  0.9666666666666667
Accuracy of Decision Tree Classifier:  0.9666666666666667


In [115]:
print("Logistic Regression Confusion Matrix:\n ")
pd.DataFrame(confusion_matrix(y_test , y_pred3) , columns = list(range(0,3)))

Logistic Regression Confusion Matrix:
 


0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [117]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred4),columns=list(range(0,3)))

Decision Tree Confusion Matrix



0   1  2
0  11   0  0
1   0  12  1
2   0   0  6