# Project Without Using Pipelines--------------------->


In [392]:
import numpy as np
import pandas as pd

In [390]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier


from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline ,make_pipeline
from sklearn.feature_selection import SelectKBest, chi2

In [296]:
df = pd.read_csv('train.csv')

In [298]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [300]:
df.drop(columns =['PassengerId','Name',"Ticket",'Cabin'] , inplace =True)

In [302]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [304]:
# Step-1 => Train Test Split

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns =['Survived']),df['Survived'],test_size = 0.2,random_state =2)


In [306]:
X_train.head(2)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
30       1    male  40.0      0      0  27.7208        C
10       3  female   4.0      1      1  16.7000        S

In [308]:
y_train.head()

30     0
10     1
873    0
182    0
876    0
Name: Survived, dtype: int64

In [310]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [312]:
# Applying Imputation-------------------------------->

si_age = SimpleImputer()
# Age me jaha par bhi missing values thi waha par Mean values aa gyi hai


si_embarked = SimpleImputer(strategy ='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.fit_transform(X_test[['Age']])
X_test_embarked = si_embarked.fit_transform(X_test[['Embarked']])

In [314]:
X_train_age  # Jaha par bhi missing values thi waha par Mean values aa gyi hai

array([[40.        ],
       [ 4.        ],
       [47.        ],
       [ 9.        ],
       [20.        ],
       [30.        ],
       [30.        ],
       [13.        ],
       [36.        ],
       [29.78590426],
       [31.        ],
       [38.        ],
       [18.        ],
       [29.78590426],
       [25.        ],
       [37.        ],
       [18.        ],
       [35.        ],
       [46.        ],
       [70.5       ],
       [48.        ],
       [48.        ],
       [24.        ],
       [56.        ],
       [54.        ],
       [29.78590426],
       [16.        ],
       [34.        ],
       [29.78590426],
       [43.        ],
       [ 2.        ],
       [50.        ],
       [60.        ],
       [41.        ],
       [ 3.        ],
       [39.        ],
       [33.        ],
       [29.78590426],
       [29.78590426],
       [37.        ],
       [42.        ],
       [19.        ],
       [16.        ],
       [29.78590426],
       [24.        ],
       [45

In [316]:
X_train_embarked

array([['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [318]:
# One Hot Encoding Sex and Embarked --------------------------------------------->

ohe_sex = OneHotEncoder(sparse_output = False ,handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse_output = False ,handle_unknown = 'ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.fit_transform(X_test_embarked)

In [320]:
X_train_sex

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [322]:
X_train_embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [324]:
X_train_remaining = X_train.drop(columns = ['Sex','Age','Embarked'])
X_test_remaining = X_test.drop(columns = ['Sex','Age','Embarked'])

In [326]:
X_train_transformed = np.concatenate((X_train_remaining,X_train_sex,X_train_embarked,X_train_age),axis =1)
X_test_transformed = np.concatenate((X_test_remaining,X_test_sex,X_test_embarked,X_test_age),axis =1)

In [328]:
X_train_transformed

array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 40.        ],
       [ 3.        ,  1.        ,  1.        , ...,  0.        ,
         1.        ,  4.        ],
       [ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 47.        ],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 71.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 29.78590426],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 29.78590426]])

In [330]:
X_train_transformed.shape

(712, 10)

In [332]:
X_test_transformed.shape

(179, 10)

In [336]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [360]:
y_pred = clf.predict(X_test_transformed)

In [362]:
y_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1], dtype=int64)

In [364]:
y_pred.shape

(179,)

In [366]:
y_pred2 = clf.predict(X_train_transformed)

In [368]:
y_pred2

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,

In [370]:
y_pred2.shape

(712,)

In [372]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.776536312849162

In [374]:
# For Exporting We use the library------------------------->

import pickle

In [382]:
# pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
# pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
# pickle.dump(clf,open('models/clf.pkl','wb'))

# Project  Using Pipelines--------------------->

In [394]:
df2 = pd.read_csv('train.csv') 

In [396]:
df2.drop(columns =['PassengerId','Name','Ticket','Cabin'],inplace = True)

In [400]:
df2.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [402]:
# Step-1 => train/test/split

X_train,X_test,y_train,y_test = train_test_split(df2.drop(columns =['Survived']),df2['Survived'],test_size = 0.2,random_state = 42)
# random_state ka use hm data ko har baar ek jaisa baatne ke liye karte hai


In [404]:
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [406]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [433]:
# Imputation Transformer---------------------------->
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy = 'most_frequent'),[6])
],remainder ='passthrough')

# Note => Here [2] and [6] are the Index numbers of 'age' and 'embarked' 

In [435]:
# One Hot Encoding------------------------------------->\
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output = False,handle_unknown ='ignore'),[1,6])
],remainder = 'passthrough')

In [437]:

# Scaling -------------------->
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [439]:
# Feature Selection ------------------------->
trf4 = SelectKBest(score_func = chi2,k=8)

# Here k=8 means hm top 8 Columns ka use kar rhe hai out of 10 columns

In [441]:
# Train the Model--------------------------------------->
trf5 = DecisionTreeClassifier()

## Create Pipeline

In [455]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [445]:
# Pipeline ki jagah ham make_pipeline bhi use kar sakte kyuki yeh simple hota hai----------------------->
# Same applies to ColumnTransformer() vs make_column_transformer()---------------------------->

#Alternate syntax
# pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [447]:
# train--------------->

# Agar aap Pipeline ke through model train nhi kar rhe ho to aap fit_transform ka use karte ho but here we train the model using Pipelin so we used 'fit'

pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x000001CA10159760>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

## Explore the Pipeline

In [451]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=8, score_func=<function chi2 at 0x000001CA10159760>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [459]:
pipe.named_steps['trf1'].transformers_

[('impute_age', SimpleImputer(), [2]),
 ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6]),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [0, 1, 3, 4, 5])]

In [461]:
pipe.named_steps['trf1'].transformers_[0]

('impute_age', SimpleImputer(), [2])

In [465]:
# pipe.named_steps['trf1'].transformers_[0][1]
pipe.named_steps['trf1'].transformers_[0][1].statistics_

array([29.49884615])

In [467]:
pipe.named_steps['trf1'].transformers_[1]

('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])

In [469]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [471]:
# Display Pipeline------------------------------------>

from sklearn import set_config
set_config(display = 'diagram')

In [475]:
# Predict -------------------------------->

y_pred2 = pipe.predict(X_test)

In [477]:
y_pred2

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [479]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6256983240223464

# Cross Validation using Pipeline

In [489]:
# Cross Validation using cross_val_score

from sklearn.model_selection import cross_val_score
cross_val_score(pipe , X_train,y_train, cv = 5, scoring = 'accuracy').mean()

0.6391214419383433

# GridSearch using Pipeline 

In [492]:
# Define parameter grid for GridSearchCV
params = {
    'trf5__max_depth': [1, 2, 3, 4, 5, None]
}

In [494]:
# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Initialize GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')

In [496]:
# Fit GridSearchCV on training data
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x000001CA10159760>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [498]:
grid.best_score_

0.6391214419383433

In [500]:
grid.best_params_

{'trf5__max_depth': 2}

# Exporting the Pipeline

In [504]:
import pickle