# Missng Indicator ------------------->

In [4]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer

In [9]:
df = pd.read_csv('train.csv', usecols=['Age','Fare',"Survived"])

In [11]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [13]:
df.isnull().mean() * 100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [15]:
X = df.drop(columns = ['Survived'])
y = df['Survived']

In [17]:
X_train , X_test, y_train,y_test = train_test_split(X , y , test_size = 0.2,random_state = 2)

In [19]:
X_train.head()

Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [23]:
si = SimpleImputer()

X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [25]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [27]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf , y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [29]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [31]:
mi.features_

array([0], dtype=int64)

In [33]:
X_train_missing = mi.transform(X_train)

In [39]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [35]:
X_test_missing = mi.transform(X_test)

In [41]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [43]:
X_train['Age_NA'] = X_train_missing

In [45]:
X_test['Age_NA'] = X_test_missing

In [51]:
X_train.head(10)

Age     Fare  Age_NA
30   40.0  27.7208   False
10    4.0  16.7000   False
873  47.0   9.0000   False
182   9.0  31.3875   False
876  20.0   9.8458   False
213  30.0  13.0000   False
157  30.0   8.0500   False
780  13.0   7.2292   False
572  36.0  26.3875   False
77    NaN   8.0500    True

In [53]:
X_test.head(19)

Age      Fare  Age_NA
707  42.0   26.2875   False
37   21.0    8.0500   False
615  24.0   65.0000   False
169  28.0   56.4958   False
68   17.0    7.9250   False
606  30.0    7.8958   False
630  80.0   30.0000   False
785  25.0    7.2500   False
660  50.0  133.6500   False
728  25.0   26.0000   False
20   35.0   26.0000   False
486  35.0   90.0000   False
15   55.0   16.0000   False
692   NaN   56.4958    True
643   NaN   56.4958    True
192  19.0    7.8542   False
65    NaN   15.2458    True
597  49.0    0.0000   False
702  18.0   14.4542   False

In [57]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [61]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2 , y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173

In [63]:
si = SimpleImputer(add_indicator = True)

In [65]:
X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [67]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2 , y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173